app.message: This is message from dev app configuration file.


spring.servlet.multipart:
  max-file-size: 3280KB
  max-request-size: 3280KB
spring:
  application:
    name: Gnemes
  data:
    mongodb:
      uri: mongodb://gnemes:123456@localhost/
      database: gnemes
server:
  port: 9090
management:
  endpoint:
    beans:
      enabled: true
    info:
      enabled: false

logging:
  level.root: debug
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

amazonProperties:
  endpointUrl: https://s3.ap-northeast-1.amazonaws.com
  accessKey: AKIAQF2OAKBLARIPMFCQ
  secretKey: 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
  UserName: user_gnemes
  bucketName: genemes-pic
  region: ap-northeast-1
  localDir: upload-dir



