version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: CheckWorkDir
          command: ls ./*    
      - run:
          command: cd ./GnemesBackEnd&&./gradlew build
      - run:
          command: cd ./GnemesBackEnd&&./gradlew assembleDebug

