app.message: This is message from dev app configuration file.
spring.servlet.multipart:
  max-file-size: 3280KB
  max-request-size: 3280KB
spring:
  application:
    name: GnemesUser
  redis:
    host: localhost
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  data:
    mongodb:
      uri: mongodb://gnemes:123456@localhost/
      database: gnemes
server:
  port: 9092
management:
  endpoint:
    beans:
      enabled: true
    info:
      enabled: false

logging:
  level.root: debug
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"